In [48]:
import numpy as np

In [49]:
a = np.array([1, 4, 5, 8], float)
print("массив NumPy:\n{}".format(a))

массив NumPy:
[1. 4. 5. 8.]


In [50]:
type(a)

numpy.ndarray

In [51]:
a.dtype

dtype('float64')

In [52]:
b = np.asarray([1, 4, 5, 8], float)
b

array([1., 4., 5., 8.])

In [53]:
Z = np.zeros(5)
Z

array([0., 0., 0., 0., 0.])

In [54]:
O = np.ones(5)
O

array([1., 1., 1., 1., 1.])

In [55]:
E = np.eye(3)
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
I = np.identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
I.fill(4)
I

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [58]:
emp = np.empty(2)
emp

array([7.74860419e-304, 7.74860419e-304])

In [59]:
a[:2]

array([1., 4.])

In [60]:
a[3]

8.0

In [61]:
a[3] = 5
a

array([1., 4., 5., 5.])

In [62]:
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
E[1,0]

0.0

In [64]:
E[1,1]

1.0

In [65]:
E[2,:]

array([0., 0., 1.])

In [66]:
E[-1:, -2:]

array([[0., 1.]])

In [67]:
E.shape, E.size, E.ndim, len(E), 0 in E

((3, 3), 9, 2, 3, True)

In [68]:
a = np.array(range(10), float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [69]:
a = np.reshape(a, (5, 2))
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [70]:
a = np.reshape(a, 10)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [71]:
a = a.reshape((5, 2))
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [72]:
a = np.array([1, 2, 3], float)

In [73]:
a.tolist()

[1.0, 2.0, 3.0]

In [74]:
list(a)

[1.0, 2.0, 3.0]

In [75]:
a = np.array([1, 2, 3], float)

In [76]:
s = a.tobytes()
s

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [77]:
np.frombuffer(s)

array([1., 2., 3.])

In [78]:
a

array([1., 2., 3.])

In [79]:
a = np.array(range(6), float).reshape((2, 3))
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [80]:
a_t = a.transpose()
a_t

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [81]:
a_T = a.T 
a_T

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [82]:
a = np.array([[1, 2, 3],
[4, 5, 6]],
float)

In [83]:
a_f = a.flatten()
a_f

array([1., 2., 3., 4., 5., 6.])

In [84]:
a_f[0] = 0

In [85]:
print(a_f)
print("")
print(a)

[0. 2. 3. 4. 5. 6.]

[[1. 2. 3.]
 [4. 5. 6.]]


In [86]:
a_r = np.ravel(a)
a_r

array([1., 2., 3., 4., 5., 6.])

In [87]:
a_r[0] = 0

In [88]:
print(a_r)
print("")
print(a)

[0. 2. 3. 4. 5. 6.]

[[0. 2. 3.]
 [4. 5. 6.]]


In [89]:
a = np.array([1, 2, 3], float)
b = np.array([4, 5], float)
a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [90]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)

In [91]:
a+b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [93]:
np.linspace(start=0, stop=1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [95]:
print(np.linspace(start=1, stop=6, num=6, endpoint=True))

[1. 2. 3. 4. 5. 6.]


In [96]:
print(np.linspace(start=1, stop=6, num=6, endpoint=False))

[1.         1.83333333 2.66666667 3.5        4.33333333 5.16666667]


In [97]:
np.logspace(start=-1, stop=1, num=20)

array([ 0.1       ,  0.1274275 ,  0.16237767,  0.20691381,  0.26366509,
        0.33598183,  0.42813324,  0.54555948,  0.6951928 ,  0.88586679,
        1.12883789,  1.43844989,  1.83298071,  2.33572147,  2.97635144,
        3.79269019,  4.83293024,  6.15848211,  7.8475997 , 10.        ])

In [98]:
a = np.array([3, 9, 15], float)
a

array([ 3.,  9., 15.])

In [99]:
lst_bin = [3, 9, 15]

In [100]:
print(np.digitize(x=a, bins=lst_bin, right=False))

[1 2 3]


In [101]:
print(np.digitize(x=a, bins=lst_bin, right=True))

[0 1 2]


In [102]:
a = np.array([4, 10, 12, 14, 16, 16, 59, 72, 78, 86])

In [104]:
np.searchsorted(a, 13)

3

In [105]:
a = np.array([9, 3, 7, 8, 3, 7, 9])

In [106]:
np.searchsorted(a, 5)

2

In [107]:
a = np.array([0, 2, 2, 1, 1, 1])
np.bincount(a)

array([1, 3, 2], dtype=int64)

In [108]:
a = np.array([0, 2, 5, 5])
np.bincount(a)

array([1, 0, 1, 0, 0, 2], dtype=int64)

In [109]:
a = np.array([[0, 0, 0, 1],
[1, 1, 1, 0],
[0, 1, 1, 1],
[0, 1, 1, 0]])

In [110]:
np.apply_along_axis(lambda x: np.argmax(np.bincount(x)), axis=0, arr=a)

array([0, 1, 1, 0], dtype=int64)

In [111]:
a = np.array([[0.1, 0.2, 0.5],
[0.2, 0.7, 0.9],
[1.3, 3.8, 2.2],
[2.8, 1.5, 1.9]])

In [112]:
row = np.array([0.4, 0.7, 0.7])

In [113]:
a = np.insert(a, 4, row, axis=0)
a

array([[0.1, 0.2, 0.5],
       [0.2, 0.7, 0.9],
       [1.3, 3.8, 2.2],
       [2.8, 1.5, 1.9],
       [0.4, 0.7, 0.7]])

In [114]:
column = np.array([0, 1, 1, 0, 0])
a = np.insert(a, 3, column, axis=1)
a

array([[0.1, 0.2, 0.5, 0. ],
       [0.2, 0.7, 0.9, 1. ],
       [1.3, 3.8, 2.2, 1. ],
       [2.8, 1.5, 1.9, 0. ],
       [0.4, 0.7, 0.7, 0. ]])

In [115]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [116]:
x = np.array([[1,2],
[3,4]])
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [118]:
np.repeat(x, 3, axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [119]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])